@startuml
title Ó°Æ¬×âÁÞ

class Movie {
	-int priceCode
}

class Rental {
	-int daysRented
	+double getCharge()
	+getFrequentRenterPoints()
}

class Customer {
	+void statement()
}

Rental "*" <-- "1" Movie
Rental "*" --> "1" Customer
@enduml